/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gregelliott
 */
public class MultipleChoiceQuiz2 extends javax.swing.JFrame {
   int ScoreValue=0;
    int CorrectValue=0;
    int IncorrectValue=0;
    int QuestionsAnsweredValue=0;
    double PercentValue=0;
    
    String textQ1;
    String textQ2;
    String textQ3;
    String textQ4;
    String textQ5;
    
    final String Q1B= "B";
    final String Q1b= "b";
    final String Q2B= "B";
    final String Q2b= "b";
    final String Q3A= "A";
    final String Q3a= "a";
    final String Q4C= "C";
    final String Q4c= "c";
    final String Q5D= "D";
    final String Q5d= "d";
    /**
     * Creates new form MultipleChoiceQuiz2
     */
    public MultipleChoiceQuiz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        lblQ1 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        lblQ5 = new javax.swing.JLabel();
        lblinstructions = new javax.swing.JLabel();
        lbl1A = new javax.swing.JLabel();
        lbl1B = new javax.swing.JLabel();
        lbl1C = new javax.swing.JLabel();
        lbl1D = new javax.swing.JLabel();
        lbl12A = new javax.swing.JLabel();
        lbl12B = new javax.swing.JLabel();
        lbl12D = new javax.swing.JLabel();
        lbl12C = new javax.swing.JLabel();
        lbl3A = new javax.swing.JLabel();
        lbl3B = new javax.swing.JLabel();
        lbl3C = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lbl4A = new javax.swing.JLabel();
        lbl4B = new javax.swing.JLabel();
        lbl4C = new javax.swing.JLabel();
        lbl4D = new javax.swing.JLabel();
        lbl5A = new javax.swing.JLabel();
        lbl5B = new javax.swing.JLabel();
        lbl5C = new javax.swing.JLabel();
        lbl5D = new javax.swing.JLabel();
        txtQ1 = new javax.swing.JTextField();
        txtQ2 = new javax.swing.JTextField();
        txtQ3 = new javax.swing.JTextField();
        txtQ4 = new javax.swing.JTextField();
        txtQ5 = new javax.swing.JTextField();
        lblScore = new javax.swing.JLabel();
        lblScoreValue = new javax.swing.JLabel();
        lblIncorrectAnswer = new javax.swing.JLabel();
        lblCorrectAnswer = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();
        lblQ1Result = new javax.swing.JLabel();
        lblQ2Result = new javax.swing.JLabel();
        lblQ3Result = new javax.swing.JLabel();
        lblQ4Result = new javax.swing.JLabel();
        lblQ5Result = new javax.swing.JLabel();
        lblQuestionsAnswered = new javax.swing.JLabel();
        lblQuestionsAnsweredValue = new javax.swing.JLabel();
        btnCheckAnswers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lbltitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lbltitle.setText("Fun Facts Multiple Choice Quiz");

        lblQ1.setText("1. What is the most common letter in the English language?");

        lblQ2.setText("2. What is the national animal of Scotland?");

        lblQ3.setText("3. What is the most commonly visited country?");

        lblQ4.setText("4. How many countries competed in the 2018 winter olympics?");

        lblQ5.setText("5. What is the smallest country in the world?");

        lblinstructions.setText("Input the letter of your answer in the corresponding text field");

        lbl1A.setText("A. \"O\"");

        lbl1B.setText("B. \"E\"");

        lbl1C.setText("C. \"S\"");

        lbl1D.setText("D. \"A\"");

        lbl12A.setText("A. Wildcat ");

        lbl12B.setText("B. Unicorn");

        lbl12D.setText("D. Dolphin");

        lbl12C.setText("C. Cow");

        lbl3A.setText("A. France");

        lbl3B.setText("B. Spain");

        lbl3C.setText("C. China");

        lbl3D.setText("D. United States");

        lbl4A.setText("A. 87");

        lbl4B.setText("B. 67");

        lbl4C.setText("C. 92");

        lbl4D.setText("D. 94");

        lbl5A.setText("A. Monaco");

        lbl5B.setText("B. Nauru");

        lbl5C.setText("C. Malta");

        lbl5D.setText("D. Vatican City");

        txtQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ1ActionPerformed(evt);
            }
        });

        txtQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ2ActionPerformed(evt);
            }
        });

        txtQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQ3ActionPerformed(evt);
            }
        });

        lblScore.setText("Score");

        lblScoreValue.setText("0");

        lblIncorrectAnswer.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblIncorrectAnswer.setText("Incorrect Answers:");

        lblCorrectAnswer.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCorrectAnswer.setText("Correct Answers:");

        lblPercent.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPercent.setText("Percentage of Questions answered Correctly:");

        lblCorrectValue.setText("0");

        lblIncorrectValue.setText("0");

        lblPercentValue.setText("0");

        lblQuestionsAnswered.setText("Questions Answered");

        lblQuestionsAnsweredValue.setText("0");

        btnCheckAnswers.setText("Check Answers");
        btnCheckAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAnswersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ4)
                            .addComponent(lblQ3)
                            .addComponent(lblQ5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbl3A)
                                .addGap(18, 18, 18)
                                .addComponent(lbl3B)
                                .addGap(35, 35, 35)
                                .addComponent(lbl3C)
                                .addGap(33, 33, 33)
                                .addComponent(lbl3D))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lbl4A)
                                .addGap(36, 36, 36)
                                .addComponent(lbl4B)
                                .addGap(38, 38, 38)
                                .addComponent(lbl4C)
                                .addGap(39, 39, 39)
                                .addComponent(lbl4D))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lbl5A)
                                .addGap(18, 18, 18)
                                .addComponent(lbl5B)
                                .addGap(18, 18, 18)
                                .addComponent(lbl5C)
                                .addGap(27, 27, 27)
                                .addComponent(lbl5D)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ5Result)
                            .addComponent(lblQ4Result)
                            .addComponent(lblQ3Result)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtQ3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addComponent(txtQ4)
                                .addComponent(txtQ5))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorrectAnswer)
                                    .addComponent(lblIncorrectAnswer))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIncorrectValue)
                                    .addComponent(lblCorrectValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCheckAnswers)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPercentValue))
                                    .addComponent(lblinstructions))
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbltitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuestionsAnswered, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblScore)
                                        .addGap(5, 5, 5))))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblQ2)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lbl12B)
                                                .addGap(30, 30, 30)
                                                .addComponent(lbl12C)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl12D)
                                        .addGap(2, 2, 2))
                                    .addComponent(lblQ1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(lbl12A))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(lbl1A)
                                    .addGap(43, 43, 43)
                                    .addComponent(lbl1B)
                                    .addGap(47, 47, 47)
                                    .addComponent(lbl1C)
                                    .addGap(27, 27, 27)
                                    .addComponent(lbl1D)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblQ1Result)
                                        .addComponent(lblQ2Result)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(txtQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScoreValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuestionsAnsweredValue, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltitle))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblScore)
                            .addComponent(lblScoreValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuestionsAnswered)
                            .addComponent(lblQuestionsAnsweredValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblinstructions)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ1)
                    .addComponent(txtQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1A)
                    .addComponent(lbl1B)
                    .addComponent(lbl1C)
                    .addComponent(lbl1D)
                    .addComponent(lblQ1Result))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ2)
                    .addComponent(txtQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl12A)
                    .addComponent(lbl12B)
                    .addComponent(lbl12D)
                    .addComponent(lbl12C)
                    .addComponent(lblQ2Result))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ3)
                    .addComponent(txtQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3A)
                    .addComponent(lbl3B)
                    .addComponent(lbl3C)
                    .addComponent(lbl3D)
                    .addComponent(lblQ3Result))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ4)
                    .addComponent(txtQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl4A)
                            .addComponent(lbl4B)
                            .addComponent(lbl4C)
                            .addComponent(lbl4D)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblQ4Result)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ5)
                    .addComponent(txtQ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5A)
                    .addComponent(lbl5B)
                    .addComponent(lbl5C)
                    .addComponent(lbl5D)
                    .addComponent(lblQ5Result))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorrectAnswer)
                            .addComponent(lblCorrectValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncorrectAnswer)
                            .addComponent(lblIncorrectValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCheckAnswers)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercent)
                    .addComponent(lblPercentValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ1ActionPerformed

    }//GEN-LAST:event_txtQ1ActionPerformed

    private void txtQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ2ActionPerformed

    private void txtQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQ3ActionPerformed

    private void btnCheckAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAnswersActionPerformed

        if(textQ1.equals("B") || textQ1.equals("b"))
        {
            ScoreValue=ScoreValue+1;
            lblScoreValue.setText(String.valueOf(ScoreValue));
            lblQ1Result.setText("Correct");
            CorrectValue=CorrectValue+1;
            lblCorrectValue.setText(String.valueOf(CorrectValue));
            QuestionsAnsweredValue= QuestionsAnsweredValue+1;
            lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
            PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
            PercentValue=PercentValue*100;
            PercentValue=Math.round(PercentValue);
            PercentValue=PercentValue/100;
            lblPercentValue.setText(String.valueOf(PercentValue));
        }
        else {
            lblQ1Result.setText("Incorrect");
            IncorrectValue=IncorrectValue+1;
            lblIncorrectValue.setText(String.valueOf(IncorrectValue));
            QuestionsAnsweredValue= QuestionsAnsweredValue+1;
            lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
            PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
            PercentValue=PercentValue*100;
            PercentValue=Math.round(PercentValue);
            PercentValue=PercentValue/100;
            lblPercentValue.setText(String.valueOf(PercentValue));
        }
         if(textQ2.equals(Q2B) || textQ2.equals(Q2b))
        {
        ScoreValue=ScoreValue+1;
        lblScoreValue.setText(String.valueOf(ScoreValue));
        lblQ2Result.setText("Correct");
        CorrectValue=CorrectValue+1;
        lblCorrectValue.setText(String.valueOf(CorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
        }
        else {
        lblQ2Result.setText("Incorrect");
        IncorrectValue=IncorrectValue+1;
        lblIncorrectValue.setText(String.valueOf(IncorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
    }
 if(textQ3.equals(Q3A) || textQ3.equals(Q3a))
        {
        ScoreValue=ScoreValue+1;
        lblScoreValue.setText(String.valueOf(ScoreValue));
        lblQ3Result.setText("Correct");
        CorrectValue=CorrectValue+1;
        lblCorrectValue.setText(String.valueOf(CorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
        }
        else {
        lblQ3Result.setText("Incorrect");
        IncorrectValue=IncorrectValue+1;
        lblIncorrectValue.setText(String.valueOf(IncorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
 }       
  if(textQ4.equals(Q4C) || textQ4.equals(Q4c))
        {
        ScoreValue=ScoreValue+1;
        lblScoreValue.setText(String.valueOf(ScoreValue));
        lblQ4Result.setText("Correct");
        CorrectValue=CorrectValue+1;
        lblCorrectValue.setText(String.valueOf(CorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
        }
        else {
        lblQ4Result.setText("Incorrect");
        IncorrectValue=IncorrectValue+1;
        lblIncorrectValue.setText(String.valueOf(IncorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
  }
   if(textQ5.equals(Q5D) || textQ1.equals(Q5d))
        {
        ScoreValue=ScoreValue+1;
        lblScoreValue.setText(String.valueOf(ScoreValue));
        lblQ5Result.setText("Correct");
        CorrectValue=CorrectValue+1;
        lblCorrectValue.setText(String.valueOf(CorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
        }
        else {
        lblQ5Result.setText("Incorrect");
        IncorrectValue=IncorrectValue+1;
        lblIncorrectValue.setText(String.valueOf(IncorrectValue));
        QuestionsAnsweredValue= QuestionsAnsweredValue+1;
        lblQuestionsAnsweredValue.setText(String.valueOf(QuestionsAnsweredValue));
        PercentValue= ((double)CorrectValue/(double)QuestionsAnsweredValue);
        PercentValue=PercentValue*100;
        PercentValue=Math.round(PercentValue);
        PercentValue=PercentValue/100;
        lblPercentValue.setText(String.valueOf(PercentValue));
        }
    }//GEN-LAST:event_btnCheckAnswersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleChoiceQuiz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAnswers;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl12A;
    private javax.swing.JLabel lbl12B;
    private javax.swing.JLabel lbl12C;
    private javax.swing.JLabel lbl12D;
    private javax.swing.JLabel lbl1A;
    private javax.swing.JLabel lbl1B;
    private javax.swing.JLabel lbl1C;
    private javax.swing.JLabel lbl1D;
    private javax.swing.JLabel lbl3A;
    private javax.swing.JLabel lbl3B;
    private javax.swing.JLabel lbl3C;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lbl4A;
    private javax.swing.JLabel lbl4B;
    private javax.swing.JLabel lbl4C;
    private javax.swing.JLabel lbl4D;
    private javax.swing.JLabel lbl5A;
    private javax.swing.JLabel lbl5B;
    private javax.swing.JLabel lbl5C;
    private javax.swing.JLabel lbl5D;
    private javax.swing.JLabel lblCorrectAnswer;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblIncorrectAnswer;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ1Result;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ2Result;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ3Result;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ4Result;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ5Result;
    private javax.swing.JLabel lblQuestionsAnswered;
    private javax.swing.JLabel lblQuestionsAnsweredValue;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreValue;
    private javax.swing.JLabel lblinstructions;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtQ1;
    private javax.swing.JTextField txtQ2;
    private javax.swing.JTextField txtQ3;
    private javax.swing.JTextField txtQ4;
    private javax.swing.JTextField txtQ5;
    // End of variables declaration//GEN-END:variables
}
